### Note: update the vm ip in the host
@host = x.x.x.x:32006

### registraton
POST http://{{host}}/model-registrations
Content-Type: application/json

{ 
    "modelId": { 
        "modelName": "TestModel1", 
        "modelVersion": "v1.0" 
    }, 
    "description": "This is a test model.", 
    "modelInformation": { 
        "metadata": {
            "author": "John Doe"
        },
        "inputDataType": "pdcp",
        "outputDataType": "pdcp" 
    } 
}

### Get All Models info
GET http://{{host}}/models
Content-Type: application/json

### Get all Models info by name
GET http://{{host}}/models?model-name=TestModel1
Content-Type: application/json

### Get all Models info by name and version
GET http://{{host}}/models?model-name=TestModel1&model-version=v1.0
Content-Type: application/json

### updated model
PUT http://{{host}}/modelInfo/12345
Content-Type: application/json

{
  "id": "12345",
  "model-id": {
    "modelName": "UpdatedModel",
    "modelVersion": "v2.0"
  },
  "description": "This is an updated model.",
  "meta-info": {
    "metadata": {
      "author": "Jane Doe"
    }
  }
}

### delete modelinfo
DELETE http://{{host}}/modelInfo/12345