openapi: 3.0.0
info:
  title: Model Management API
  description: API for managing machine learning models (register, retrieve, update, delete, upload, and download).
  version: 1.1.0

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Model Management
    description: Endpoints for managing models

paths:
  /registerModel:
    post:
      tags:
        - Model Management
      summary: Register a new model
      operationId: registerModel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelInfo'
      responses:
        '200':
          description: Model registered successfully and returned object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelInfo'
        '400':
          description: Invalid request, bad input data
        '500':
          description: Internal Server Error
