openapi: 3.0.0
info:
  title: Model Management API
  description: API for managing machine learning models (register, retrieve, update, delete, upload, and download).
  version: 1.1.0

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Model Management
    description: Endpoints for managing models